<?php
// $Id: sites/all/modules/colorpicker/examples/colorpicker_example.install 1.3 2010/02/18 14:51:53EST Linda M. Williams (WILLIAMSLM) Production  $

/*
 * @file
 */

/*
 * Implementation of hook_uninstall().
 */
function colorpicker_example_uninstall() {
  variable_del('colorpicker_example_textfield_1');
  variable_del('colorpicker_example_textfield_2');
  variable_del('colorpicker_example_textfield_3');
  variable_del('colorpicker_example_textfield_4');
}
